name: Deploy WordPress

on:
  push:
    branches:
      - main  # Adjust based on branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory and Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.200.83.50 >> ~/.ssh/known_hosts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Sync files with rsync
        run: |
          rsync -avz --exclude '.git' . ubuntu@13.200.83.50:/var/www/html/wordpress
