name: Deploy WordPress

on:
  push:
    branches:
      - main  # Adjust based on branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

      - name: Add server to SSH known_hosts
        run: |
          ssh-keyscan -H 13.200.83.50 >> ~/.ssh/known_hosts

      - name: Sync files with rsync
        run: |
          rsync -avz --exclude '.git' . ubuntu@13.200.83.50:/var/www/html/wordpress
